### ISSUE TITLE
Unhelpful error msg when attempting a nonexistent city

### ISSUE THREAD

**Issue by lahdjirayhan** [Milind220/Ozone#66]
Windows 7, Python 3.8.5, dev branch

---
```python
>>> import ozone as ooo
>>> o3 = ooo.Ozone(WAQI_TOKEN)
>>> o3.get_city_air('nonexistent_city')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\git-line\milind-ozone\ozone\src\ozone\ozone.py", line 318, in get_city_air
    row = self._parse_data(data_obj, city, params)
  File "e:\git-line\milind-ozone\ozone\src\ozone\ozone.py", line 162, in _parse_data
    row["latitude"] = data_obj["city"]["geo"][0]
TypeError: string indices must be integers
>>>
```

---

Might've been what is discussed in #58. In any case, there should be a more helpful error message.

**Comment by Milind220** [comment]
@lahdjirayhan Hey! Thanks for filing this issue. It's a good catch, that's a pretty meaningless error message.
It's unrelated to the other issue.

We need to improve error messages for every method of the package actually.

If you'd like to address this issue, we'd love that! Let us know and we'll assign it to you

**Comment by lahdjirayhan** [comment]
Sure. I'll try to address it.
